### 
GET http://localhost:3333/courses

###
GET http://localhost:3333/courses/1c4a3595-ec87-455d-9cf7-656982d8a6ae


###
POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de TypeScript"
}
